  # SITE CONFIGURATION
baseurl: ""
url: "http://yurybubnov.com/"
title: Yury Bubnov # site's title
description: "Let's make it work" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Let's make it work # blog's title
#  avatar: http://www.gravatar.com/avatar/85fd024c73e944597d45f0997f6faad8.png
  favicon: assets/favicon.ico
  gravatar: 85fd024c73e944597d45f0997f6faad8 # Email MD5 hash

  # Header and footer text
#  header_text: > #two or three lines to describe your site
#     <p>Change header text in <code>_config.yml</code> <br> to update this feature.</p>
#  header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
   Copyright 2018

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email: ybubnov@gmail.com
  facebook: ybubnov
  github: yurybubnov
  linkedin: https://www.linkedin.com/in/bubnov/
  twitter: yurybubnov
  
  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    tumblr:
    pinterest:
    pocket:
    reddit: true
    linkedin: true
    wordpress:
    email: true

  # Scripts / Features 
  google_analytics: UA-57927955-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  
  special_page:
    search: 
      icon: "search"
      enabled: true
    tags:
      icon: "tags"
      enabled: true
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]
